apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc
  namespace: calc
spec:
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calc
        image: htoahifaz11/calc:v1
        ports:
        - containerPort: 5000